# This is a basic workflow to help you get started with Actions

name: CI_for_Dev

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a single command using the runners shell
    # And of course we need to goto our functions folder to deploy
    - name: Install npm packages
      run: |
        cd functions
        npm install --force
        npm run build
    # We must choose a project
    - name:  Set project DEV
      run: npx firebase-tools use telegram-bot-boilerplate
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    # Run test coverage
    - name: Run tests
      run: |
          cd ./functions
          npm run test:c          
    # Deploying the functions to firebase
    - name:  Deploy to Firebase
      run: npx firebase-tools deploy --only functions
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}